version: '2.4'
services:
  nxfilter: 
    build: .  
    image: sregor/nxfilter:v1.0
    mem_limit: 1024m
    ports: 
      - "10443:80"
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "19001-19004:19001-19004" 
    container_name: nxfilter
    volumes:
      - nxfilter-conf:/nxfilter/conf
      - nxfilter-log:/nxfilter/log 
      - nxfilter-db:/nxfilter/db
    restart: always 
volumes: 
  nxfilter-conf:
  nxfilter-log:
  nxfilter-db:
